---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subquery-node
  namespace: chainbridge-subquery
spec:
  selector:
    matchLabels:
      app: subquery-node
  template:
    metadata:
      labels:
        app: subquery-node
    spec:
      containers:
        - name: subquery-node
          image: phala/chainbridge-subql-node
          env:
            - name: DB_DATABASE
              value: subquery
            - name: DB_HOST
              value: postgres
            - name: DB_PASS
              value: subquery
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: subquery
            - name: NETWORK_ENDPOINT
              value: wss://khala.phala.network/ws
            - name: NETWORK_TYPEDEFS
              value: khala
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "0"
              cpu: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: subquery-node
  namespace: chainbridge-subquery
spec:
  selector:
    app: subquery-node
  ports:
    - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subquery-query
  namespace: chainbridge-subquery
spec:
  selector:
    matchLabels:
      app: subquery-query
  template:
    metadata:
      labels:
        app: subquery-query
    spec:
      containers:
        - name: subquery-query
          image: onfinality/subql-query
          args:
            - --indexer=http://subquery-node:3000
            - --name=app
            - --playground
          env:
            - name: DB_DATABASE
              value: subquery
            - name: DB_HOST
              value: postgres
            - name: DB_PASS
              value: subquery
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: subquery
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "0"
              cpu: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: subquery-query
  namespace: chainbridge-subquery
spec:
  selector:
    app: subquery-query
  ports:
    - port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: chainbridge-subquery
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.3-alpine
          env:
            - name: POSTGRES_DB
              value: subquery
            - name: POSTGRES_PASSWORD
              value: subquery
            - name: POSTGRES_USER
              value: subquery
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "0"
              cpu: "0"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgres/data
              subPath: postgres-data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: chainbridge-subquery
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: chainbridge-subquery
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
